rubyapi/config/routes.rb
Rails.application.routes.draw do
  resources :cts
  get 'welcome/index'
  root 'welcome#index'

end

rubyapi/app/models/ct.rb
class Ct < ActiveRecord::Base
end

rubyapi/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception


before_filter :allow_ajax_request_from_other_domains

 def allow_ajax_request_from_other_domains
   headers['Access-Control-Allow-Origin'] = '*'
   headers['Access-Control-Request-Methods'] = '*'
   headers['Access-Control-Allow-Headers'] = '*'
 end

end

rubyapi/app/controllers/cts_controller.rb
class CtsController < ApplicationController
  before_action :set_ct, only: [:show, :edit, :update, :destroy]

  # GET /cts
  # GET /cts.json
  def index
    @cts = Ct.all
  end

  # GET /cts/1
  # GET /cts/1.json
  def show
  end

  # GET /cts/new
  def new
    @ct = Ct.new
  end

  # GET /cts/1/edit
  def edit
  end

  # POST /cts
  # POST /cts.json
  def create
    @ct = Ct.new(ct_params)

    respond_to do |format|
      if @ct.save
        format.html { redirect_to @ct, notice: 'Ct was successfully created.' }
        format.json { render :show, status: :created, location: @ct }
      else
        format.html { render :new }
        format.json { render json: @ct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cts/1
  # PATCH/PUT /cts/1.json
  def update
    respond_to do |format|
      if @ct.update(ct_params)
        format.html { redirect_to @ct, notice: 'Ct was successfully updated.' }
        format.json { render :show, status: :ok, location: @ct }
      else
        format.html { render :edit }
        format.json { render json: @ct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cts/1
  # DELETE /cts/1.json
  def destroy
    @ct.destroy
    respond_to do |format|
      format.html { redirect_to cts_url, notice: 'Ct was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ct
      @ct = Ct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ct_params
      params.require(:ct).permit(:title, :name, :description, :url)
    end
end

rubyapi/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

rubyapi/app/helpers/application_helper.rb
module ApplicationHelper
end

rubyapi/app/helpers/cts_helper.rb
module CtsHelper
end

rubyapi/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rubyapi/app/views/cts/_form.html.erb
<%= form_for(@ct) do |f| %>
  <% if @ct.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ct.errors.count, "error") %> prohibited this ct from being saved:</h2>

      <ul>
      <% @ct.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rubyapi/app/views/cts/edit.html.erb
<h1>Editing Ct</h1>

<%= render 'form' %>

<%= link_to 'Show', @ct %> |
<%= link_to 'Back', cts_path %>

rubyapi/app/views/cts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Name</th>
      <th>Description</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cts.each do |ct| %>
      <tr>
        <td><%= ct.title %></td>
        <td><%= ct.name %></td>
        <td><%= ct.description %></td>
        <td><%= ct.url %></td>
        <td><%= link_to 'Show', ct %></td>
        <td><%= link_to 'Edit', edit_ct_path(ct) %></td>
        <td><%= link_to 'Destroy', ct, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ct', new_ct_path %>

rubyapi/app/views/cts/new.html.erb
<h1>New Ct</h1>

<%= render 'form' %>

<%= link_to 'Back', cts_path %>

rubyapi/app/views/cts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ct.title %>
</p>

<p>
  <strong>Name:</strong>
  <%= @ct.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ct.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @ct.url %>
</p>

<%= link_to 'Edit', edit_ct_path(@ct) %> |
<%= link_to 'Back', cts_path %>

rubyapi/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Act</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

rubyapi/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>